### ISSUE TITLE
the `no-section-label` should be removed from book.toml IMO

### ISSUE THREAD

**Issue by Genesis3800** [foundry-rs/book#1008]
The _`no-section-label`_ value being set to `true` removes the numerical numbering of the sections of the book.
Is there any specific reason this is done in the Foundry book.
In my opinion, the numbering makes everything look more organized.

The first image is from [mdbook's official documentation](https://rust-lang.github.io/mdBook/format/configuration/renderers.html?highlight=no-section-label#html-renderer-options), the second is from the Foundry book:
![image](https://github.com/foundry-rs/book/assets/56264430/c10914b4-504f-4eac-ac4e-c51c360d8dba)
![image](https://github.com/foundry-rs/book/assets/56264430/62fc0c35-bcf2-43c0-a023-a360b4dfd3c8)

I propose removing this value from `book.toml`.
I would like to make a PR for this, lemme know if this is something that could be implemented.

**Comment by mattsse** [comment]
> Is there any specific reason this is done in the Foundry book.

no reason, I'd accept a PR for that

**Comment by Genesis3800** [comment]
Thank you @mattsse ,
I am a big ass fan of Foundry, and would love to start contributing to the book with a small PR.

I'll send in a PR ASAP.

**Comment by Genesis3800** [comment]
Hey @mattsse ,

I forked the repo and pushed the required change to it.

[https://github.com/Genesis3800/book](https://github.com/Genesis3800/book)

I want to run it on a Github pages server to see if I made any unexpected errors. How can I run the workflow files? I configured my GitHub pages to deploy from actions, but not sure how to actually run one of those workflows.

**Comment by Genesis3800** [comment]
> you can run locally with `mdbook serve` see readme

Yeah already did that.

Mdbook serve works fine. Creating PR now.
