### ISSUE TITLE
args in script?

### ISSUE THREAD

**Issue by pedrohba1** [foundry-rs/book#1012]
I have a script like this:

```
	forge script scripts/DeployFromDeployer.s.sol:Deploy --fork-url ${RPC_URL}  --broadcast -vvvv
```

can I pass --constructor-args in a script? Or any args at all? I couldn't find much about constructor args or passing args to scripts. I can read them from a file, although. But I would like to set them from the command line. Is this achievable? 

I know that hardhat has this concept called tasks, which does pretty much what I'm defining: https://hardhat.org/hardhat-runner/docs/advanced/create-task#creating-a-task

**Comment by 0xf1b0** [comment]
I also was looking for a way to do this. As far as I understand, now this can only be done using the `--sig` option.

```
-s, --sig <SIG>
        The signature of the function you want to call in the contract, or raw
        calldata

        [default: run()]
```

By default when you run a script, the `run()` function in this script is called. But you can specify any function you want using `--sig` option. To call a function with input parameters you need to use raw calldata.

To make it easier to obtain calldata, you can use another tool that comes with foundry - `cast`.

For example your deploy script has a function like this:
```solidity
function run(uint256 arg1, bool arg2) external { ... }
```

To get calldata to run it, use the command:
```bash
cast calldata "run(uint256,bool)" 1 true
```
Now you can run your script like this:
```bash
forge script scripts/DeployFromDeployer.s.sol:Deploy \
    --fork-url ${RPC_URL}  --broadcast -vvvv \
    --sig 0x0a3395f500000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001
```
Can be combined into oneliner:
```bash
forge script scripts/DeployFromDeployer.s.sol:Deploy \
    --fork-url ${RPC_URL}  --broadcast -vvvv \
    --sig $(cast calldata "run(uint256,bool)" 1 true)
```
