### ISSUE TITLE
Add `--account` to `forge script` options?

### ISSUE THREAD

**Issue by yotam-oinc** [foundry-rs/book#1017]
From what I can tell, the `--account` argument is supported in `forge script` but is missing from the documentation: 
https://github.com/foundry-rs/book/blob/master/src/reference/common/multi-wallet-options-keystore.md

Should this be changed to use the args from the `cast send` docs?
https://github.com/foundry-rs/book/blob/master/src/reference/common/wallet-options-keystore.md

I'm not sure what's the difference between `wallet-options` and `multi-wallet-options` snippets and why they are separated. So maybe need to just copy the `--account` arg from `wallet-options` to `multi-wallet-options` ?

**Comment by ATREAY** [comment]
hey @yotam-oinc, can I work on this issue if you're not already on it?

**Comment by Tudmotu** [comment]
@ATREAY I'm not sure how the Foundry people would like to handle this. In any case, I am not working on this.

**Comment by Evalir** [comment]
feel free to work for it @ATREAY ! will assign

**Comment by ATREAY** [comment]
Hey @Evalir, I've implemented the necessary changes. Could you please review them when you have a moment?

**Comment by Tudmotu** [comment]
Thank you @ATREAY :pray:
