### ISSUE TITLE
Proposing a new tutorial

### ISSUE THREAD

**Issue by Genesis3800** [foundry-rs/book#1020]
Hey guys, 
I made a small PR to the book a week ago, and I think I have a good idea for a new tutorial for the book.

Problem statement:
I feel like a good end-to-end tutorial on CREATE2 is still lacking.

I propose a full CREATE2 tutorial in Foundry that covers:

1. What is CREATE2, a brief explanation.
2. Explaining a CREATE2 factory implementation (maybe one of the existing popular implementations).
3. Deploying the factory contract on Sepolia using the normal script deployment method.
4. Use the deployed factory to finally deploy the factory contract at a deterministic address.
5. Repeat steps 3 and 4 for Mumbai to show how to deploy the same contract across multiple chains at the same address.
6. Write a few simple test functions meant to be ran in a fork test.

Lemme know if this is something you guys can get behind. I will probably need help along the way.
To emphasise that I have writing experience I will link 2 of my works:

[https://docs.chainstack.com/docs](https://docs.chainstack.com/docs)
[https://www.solidity-in-foundry.com/](https://www.solidity-in-foundry.com/)

I would love it if you guys could accept this.

**Comment by mattsse** [comment]
definitely, always appreciate new examples

**Comment by Genesis3800** [comment]
Thank you @mattsse , two things pls:

1. Is this issue a good place to ask for help if I need to?
2. Is the table of contents that I proposed roughly acceptable? As in can I adhere to that while prepping my first draft?

**Comment by Evalir** [comment]
Hey @Genesis3800!

1. Yep, you can ask here. Another good way of doing it would be doing an initial draft, then opening the draft PR, and asking there as well!
2. Yes it sounds good!

**Comment by Genesis3800** [comment]
@Evalir do you have a specific CREATE2 implementation that folks at Foundry prefer?
I found [this one by Arachnid]( https://github.com/Arachnid/deterministic-deployment-proxy) to be referenced a lot.

Maybe point me towards something that you guys like?

**Comment by Evalir** [comment]
Yep, Nick's implementation (the one you linked) is the one we used at foundry and is available on scripts, and on anvil by default. It has the interface we expect.

**Comment by Genesis3800** [comment]
Great I'll use this implementation to write the tutorial. Maybe will reach out to Nick to update the repo's README with updated deployment addresses.
Thanks for the help Evalier. Now I'll trouble you again only when I have made some progress.

**Comment by Genesis3800** [comment]
Hey guys @mattsse @Evalir ,
is there some documentation on how to deploy contracts written in pure yul using Foundry?

Specifically, I want to deploy [Nick's implementation](https://github.com/Arachnid/deterministic-deployment-proxy/blob/master/source/deterministic-deployment-proxy.yul) as it is, but am not sure what is the best way to deploy this since the usual scripting will obviously not work.

Also is it even possible to verify pure yul contracts using Forge?

**Comment by Genesis3800** [comment]
Guys, @mattsse @Evalir 
I am totally stuck 😔😔😔

Cannot figure out how to compile Nicks's CREATE2 proxy since it is in pure Yul.
Tried using an existing [YulDeployer](https://github.com/deliriusz/foundry-yul-puzzles/blob/main/test/lib/YulDeployer.sol), but no luck.

Could use some help here.

Actually, this tutorial could be good for Foundry because currently there is no tutorial on how to compile pure YUL code in Foundry.

**Comment by Genesis3800** [comment]
One workaround I can think of is to use [OpenZeppelin's CREATE2 implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e12511b53eb6ec99d86acec76b0923acfa5b8da2/contracts/utils/Create2.sol#L8).

It's much better in terms of readability IMO.
Lemme know if this works for you guys.

Should have a draft by tomorrow if I can work with OpenZeppelin's implementation.

**Comment by Genesis3800** [comment]
Dunno if anyone's listening, but finally after a lot of fuckin grind, I was able to make a really cool CREATE2 tutorial, based on this library implementation by OpenZeppelin:
[https://github.com/OpenZeppelin/openzeppelin-contracts/blob/793d92a3331538d126033cbacb1ee5b8a7d95adc/contracts/utils/Create2.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/793d92a3331538d126033cbacb1ee5b8a7d95adc/contracts/utils/Create2.sol)

Really fuckin stoked. Now the easy part. Writing the tutorial in MD.
Creating a PR soon.
