### ISSUE TITLE
Updating integration with Hardhat

### ISSUE THREAD

**Issue by DaigaroCota** [foundry-rs/book#1033]
It's been a while since the integration with Hardhat page was updated in the Foundry Book.

In fact Hardhat has improved and created a plug in that makes integration more clean than the current process suggested in the Foundry book.

Please check it out here:
https://hardhat.org/hardhat-runner/docs/advanced/hardhat-and-foundry

**Comment by Evalir** [comment]
thanks! wanna try and take this on?

**Comment by Genesis3800** [comment]
Hey @Evalir , I would like to take this on if this isn't being worked on by anyone else.
I just contributed a tutorial to the book, so you know I'm good for it.
[https://book.getfoundry.sh/tutorials/create2-tutorial](https://book.getfoundry.sh/tutorials/create2-tutorial)

Lemme know if you're ok with me taking this.

**Comment by Genesis3800** [comment]
@Evalir polite bump pls.

**Comment by Evalir** [comment]
Sounds good @Genesis3800, go for it!

**Comment by Genesis3800** [comment]
Heck yeah, this is mine now. Will make a PR ASAP.
