### ISSUE TITLE
Document the order in which assertions are reported on test failures

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/book#1036]
In most test frameworks, the first test assertion to fail is the one reported. In foundry, the last test assertion to fail (that comes from DSTest or cheatcodes) is the one to be reported. This should be documented in a "debugging with foundry" or existing suitable section.

**Comment by ATREAY** [comment]
Hey @Evalir, is it okay if I work on this issue if it's available? Also, can you confirm if the page I've linked below is the right place to add this information, or should it go somewhere else?

[Debugger](https://book.getfoundry.sh/forge/debugger?highlight=debugging%20with%20foundry#debugger)

**Comment by Evalir** [comment]
Closed by https://github.com/foundry-rs/book/pull/1058
