### ISSUE TITLE
[FAIL. Reason: revert: INITIALIZATION_FAILED]

### ISSUE THREAD

**Issue by SvenMeyer** [foundry-rs/book#1060]
I have some strange errors `[FAIL. Reason: revert: INITIALIZATION_FAILED]` and nowhere I can find/google some information about it.

I have a factory deploying a ERC20 (actually xERC20 token), working fine so far, made some changes which should not affect this code (replaced Ownable with AccessControl)

It looks like these errors may not have much to do with the code or show up at least asynchronously.

Like, I have this simple test 
```solidity
contract UnitNames is Base {
  function testName() public {
    assertEq('Test', _xerc20.name());
  }

  function testSymbol() public {
    assertEq('TST', _xerc20.symbol());
  }
}
``` 
If I run unit and e2e tests, this error shows up between the two (apparently successful) tests ... and also in later tests.

![image](https://github.com/foundry-rs/book/assets/25609/1e297fa1-2d12-40d1-a34a-c73161e1cbc6)

If I just run the unit tests , at least the two simple tests run fine ... (No `[FAIL. Reason: revert: INITIALIZATION_FAILED]` messages between these two tests).

![image](https://github.com/foundry-rs/book/assets/25609/41220389-5aa1-4d0d-a8f6-79e9871caddd)

**Comment by Evalir** [comment]
Right, this seems like it might be an user bug as this comes from solmate—mind if we take this to the foundry telegram chat so we or other people can help you? This way we keep the issue tracker clean. Thanks!
