### ISSUE TITLE
how to test contracts like remix?

### ISSUE THREAD

**Issue by cell0901** [foundry-rs/book#1073]
i wrote a contract in vs code already installed foundry forge its working fine.
now i want to test the contract and the function i wrote in it, like i can test on remix ui. But how to do so?

don't criticise me i am just a beginner.

**Comment by Evalir** [comment]
Hi! I think this question is better suited for the telegram chat: https://t.me/foundry_support

There's many options to choose from to test your contract: you can deploy it to a test network, or an anvil instance. We can help you further on the support chat ^^

Closing this as it's not book related
