### ISSUE TITLE
Remove Goerli and update with Sepolia testnet

### ISSUE THREAD

**Issue by allwin199** [foundry-rs/book#1077]
[deploying-our-contract](https://book.getfoundry.sh/tutorials/solidity-scripting?highlight=goerli#deploying-our-contract)

Examples of deploying smart contracts contain details about the "Goerli" testnet

I think it should be updated to the "Sepolia" network

If this update needs to be made, I am willing to contribute.

**Comment by Evalir** [comment]
definitely needs to be made @allwin199 — feel free to take it!

**Comment by allwin199** [comment]
@Evalir  [Faucets](https://faucet.paradigm.xyz/) In this faucet link, there is no Sepolia testnet available.

Let me know If I have to link any other faucets.

**Comment by yash251** [comment]
> deploying-our-contract

you can use https://sepoliafaucet.com/

**Comment by allwin199** [comment]
@Evalir can you confirm that I can include the above faucet in the docs

**Comment by Evalir** [comment]
@allwin199 feel free to go ahead, i can review once you have the pr
