### ISSUE TITLE
Documentation recommend forge init instead of forge create

### ISSUE THREAD

**Issue by NandyBa** [foundry-rs/book#1084]
Documentation (cf: [creating-a-new-project.md](https://github.com/foundry-rs/book/blob/master/src/projects/creating-a-new-project.md)) indicate to run `forge init hello_foundry` to create a new Foundry project.

Yet I run `forge init <project_name>`it's raise this error:`Error: ’init’ is not a Forge command.`

So I check `forge --help`and find that only `forge create`existe no `forge init`

**Comment by DaniPopes** [comment]
`forge init` is very much a forge command: <https://book.getfoundry.sh/reference/cli/forge/init>
You may either have the wrong `forge` binary or an extremely outdated version.

**Comment by NandyBa** [comment]
Strange, I just run `curl -L https://foundry.paradigm.xyz | bash`. I will check forge version

**Comment by NandyBa** [comment]
`forge --version` return 6.15.0.
I must correspond to a old version.

**Comment by DaniPopes** [comment]
You have a different forge binary, see `which -a forge`. It might've been installed previously with `apt`.
