### ISSUE TITLE
Make all the external links open in new tab by default

### ISSUE THREAD

**Issue by nirban256** [foundry-rs/book#1096]
I am raising this issue because many of the links which refers to the external websites gets opened in the same tab upon the [Foundry book](https://book.getfoundry.sh/) website  which creates a problem especially when learning something from a tutorial or coding along with a tutorial.

For example,
We can see in the **[Dockerizing a Foundry project](https://book.getfoundry.sh/tutorials/foundry-docker#dockerizing-a-foundry-project)** tutorial under the **Installation and setup** on the fourth paragraph where the link of **[Ethereum's article](https://ethereum.org/en/developers/docs/nodes-and-clients/nodes-as-a-service/)** is present. If it opens in a  new tab it would be more easier for me to read the whole tutorial as I wouldn't have to switch back and forth between pages.

**Comment by mattsse** [comment]
there must be a mdbook setting for this, but I'm not sure

**Comment by Sabnock01** [comment]
Believe the only way to accomplish this is with HTML. Open to doing this but would be convenient if there was a way to enforce it.

eg.
```md
[Awesome Foundry](https://github.com/crisgarner/awesome-foundry)
``` 
to
```html
<a href="https://github.com/crisgarner/awesome-foundry" target="_blank">Awesome Foundry</a>
```

**Comment by nirban256** [comment]
the issue is fixed now, thanks for implementing it @onbjerg
