### ISSUE TITLE
Document new `ignored_warnings_from` (`ignored_file_paths`) config setting

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/book#1114]
ref https://github.com/foundry-rs/foundry/pull/7063

https://book.getfoundry.sh/reference/config/solidity-compiler

cc @loocapro

**Comment by mattsse** [comment]
assigned, ty

**Comment by zerosnacks** [comment]
Hi @mabsattar are you still interested in working on this?

**Comment by mabsattar** [comment]
hi @zerosnacks  thank you for reminding me, i just saw this is still pending.
Can I please give it a try now ?
I'll try to get this fix ASAP and will update you.

**Comment by mabsattar** [comment]
hi @zerosnacks thank you for reminding me, I just saw that this is still pending.
Can I work on it now and fix it ASAP.
I'll update you once its done or if I face any issues.

**Comment by zerosnacks** [comment]
Thanks @mabsattar, no worries

**Comment by mabsattar** [comment]
Hi @mattsse @zerosnacks , sent the PR for this, please let me know if any changes needed. thanks
