### ISSUE TITLE
Solidity Scripting Tutorial code incompatible with v5 OpenZeppelin Ownable class

### ISSUE THREAD

**Issue by frankmullenger** [foundry-rs/book#1119]
The Solidity Scripting Tutorial example code doesn't compile when the latest version of the OpenZeppelin library is used. 

Installing OpenZeppelin library [using the instructions: ](https://github.com/foundry-rs/book/blob/master/src/tutorials/solidity-scripting.md?plain=1#L35)`forge install transmissions11/solmate Openzeppelin/openzeppelin-contracts` seems to install the latest version of the OpenZeppelin library (v5), possibly because the [ref defaults to "master"](https://book.getfoundry.sh/reference/forge/forge-install)?

The function signature of the OpenZeppelin Ownable class has changed in v5 from v4, the [constructor now requires an "initialOwner" parameter](https://github.com/OpenZeppelin/openzeppelin-contracts/compare/v4.9.5...master#diff-12d832c90ed93f8f3de2bdb5d70c7f18a00a7ee6ab685510c2f4c88510d32180R38). 

So the example code in the Tutorial is [missing a call to the base constructor in Ownable](https://github.com/foundry-rs/book/blob/master/src/tutorials/solidity-scripting.md?plain=1#L73).

The compilation error (using Solc 0.8.22) is:
```bash
Error: 
Compiler run failed:
Error (3415): No arguments passed to the base constructor. Specify the arguments or mark "NFT" as abstract.
  --> src/NFT.sol:13:1:
   |
13 | contract NFT is ERC721, Ownable {
   | ^ (Relevant source part starts here and spans across multiple lines).
Note: Base constructor parameters:
  --> lib/openzeppelin-contracts/contracts/access/Ownable.sol:38:16:
   |
38 |     constructor(address initialOwner) {
   |   
``` 

Possibly the NFT constructor could call the base constructor?
```solidity
constructor(
    string memory _name,
    string memory _symbol,
    string memory _baseURI
) ERC721(_name, _symbol) Ownable(msg.sender) {
    baseURI = _baseURI;
}
```
Or possibly the dependency could specify a version?
```bash
forge install transmissions11/solmate Openzeppelin/openzeppelin-contracts@v4.9.5
```

**Comment by Evalir** [comment]
We could also update the tutorial—would you be up for it @frankmullenger ?

**Comment by frankmullenger** [comment]
@Evalir Yeah I'd be happy to open a pull request for this 😃

**Comment by Evalir** [comment]
awesome! will assign to you @frankmullenger
