### ISSUE TITLE
Document the `--ast` flag as an option for `forge build`

### ISSUE THREAD

**Issue by adamegyed** [foundry-rs/book#1134]
As of https://github.com/foundry-rs/foundry/pull/7197, the AST is no longer included in the compiler output unless specified with `--ast` or `--build-info`. Currently, the `--ast` flag is undocumented, and should be added to places where it can be specified as an option. This includes `forge build`, and might include other commands that run `forge build` internally like `forge test` or `forge script`.

**Comment by zerosnacks** [comment]
Ticket can be closed, this has been fixed as part of the automated workflow introduced in #1135

https://book.getfoundry.sh/reference/cli/forge/build

**Comment by zerosnacks** [comment]
Marking as resolved
