### ISSUE TITLE
Foundry book contains invalid command for witnessing lib structure after dependency installation

### ISSUE THREAD

**Issue by 0xumarkhatab** [foundry-rs/book#1149]
# Main issue
[Chapter 5 of foundry book](https://book.getfoundry.sh/projects/dependencies#adding-a-dependency) contains an invalid command for latest version of foundry which when ran , gives following error message

![image](https://github.com/foundry-rs/book/assets/71306738/67fe2b6c-49dd-45a2-8e81-a9377fdefa22)

## To Reproduce
- open Powershell, in a foundry project.
- Install some dependency like solmate ( ` forge install transmissions11/solmate` )
- run `tree lib -L 1` at the root level

# My system specs
## Forge Version
 forge 0.2.0 (9fe9a3fc 2024-02-22T13:23:11.369603400Z)
## Terminal
Powershell
## OS 
Windows 10
## Rustc Version
rustc 1.76.0 (07dca489a 2024-02-04)
## Cargo Version
cargo 1.76.0 (c84b36747 2024-01-18)

**Comment by zerosnacks** [comment]
Unable to replicate on Linux / MacOS, this is likely because the Windows `tree` command likely uses different parameters and doesn't recognize `-L`.

Feel free to open a PR for this documenting the behaviour on Windows.

**Comment by zerosnacks** [comment]
Marking as `not planned`, there is no claim of commands being Windows compatible
