### ISSUE TITLE
chore: prefer named imports over default imports in examples

### ISSUE THREAD

**Issue by 0xumarkhatab** [foundry-rs/book#1150]
Chapter 8 -> section 8.1 lacks import of stdError  & Vm

## Issue

There are multiple places where forge-std's components are used without importing them .

1. Lack of stdError and Vm import
```
A good practice is to use the pattern test_Revert[If|When]_Condition in combination with the [expectRevert](https://book.getfoundry.sh/cheatcodes/expect-revert.html) cheatcode (cheatcodes are explained in greater detail in the following [section](https://book.getfoundry.sh/forge/cheatcodes.html)). Also, other testing practices can be found in the [Tutorials section](https://book.getfoundry.sh/tutorials/best-practices.html). Now, instead of using testFail, you know exactly what reverted and with which error:

    function test_CannotSubtract43() public {
        vm.expectRevert(stdError.arithmeticError);
        testNumber -= 43;
    }
```

## Impact 
Beginners get confused when stdError is not found upon compilation of smart contracts because foundry demands explicit imports

## Fix
Add following lines in the docs to import used components

```solidity
import {Vm} from "forge-std/Vm.sol";
import {stdError} from "forge-std/StdError.sol";

```

**Comment by zerosnacks** [comment]
If you import as follows: `import "forge-std/Test.sol";`, as mentioned at the start, it will work

That said, I think we should modify the example code to reflect the best practices (e.g. named imports), especially as this is the entrypoint for beginners. We should also update the Solidity pragma to use `pragma solidity ^0.8.13;` to reflect the one generated by `forge init`.

@0xumarkhatab would you like to open a PR for this?

**Comment by zsskar** [comment]
Can I fix this little issue ?

**Comment by onbjerg** [comment]
Yes, feel free!

**Comment by zerosnacks** [comment]
Hi @zsskar would be great to get this fixed, do you still have time to work on it?

**Comment by zerosnacks** [comment]
Updated the title, resolving this by replacing default imports with named imports

https://github.com/foundry-rs/book/pull/1298
