### ISSUE TITLE
bug: incorrect link in solmate example

### ISSUE THREAD

**Issue by letmejustputthishere** [foundry-rs/book#1183]
the url [here](https://github.com/foundry-rs/book/blob/ce0833c40aaa3f5f08d37c684661aa1267b4d9ac/src/tutorials/solmate-nft.md?plain=1#L188) doesn't really help me figure out how to provide a URL to the constructor at deployment

**Comment by zerosnacks** [comment]
Should be updated to https://docs.opensea.io/docs/deploying-a-seadrop-compatible-contract
