### ISSUE TITLE
Add guide for EIP-712 signatures with vm.sign / vm.addr

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/book#159]
Explain how EIP712 works and create & verify signatures via the sign & addr cheatcodes https://github.com/Rari-Capital/solmate/blob/7c34ed021cfeeefb1a4bff7e511a25ce8a68806b/src/test/ERC20.t.sol#L89-L103

**Comment by tbtstl** [comment]
@onbjerg Are you actively working on this? Happy to dig in now if you'd like, we're actively working on this for a [ZORA PR](https://github.com/ourzora/v3/pull/160)

**Comment by onbjerg** [comment]
@tbtstl Feel free to take it on! I just assigned myself to a bunch of issues I'm going to address soon, but the more the merrier 😄

**Comment by onbjerg** [comment]
Hey @tbtstl, just pinging to hear if you're still working on this :blush:

**Comment by kulkarohan** [comment]
hey @onbjerg, yup just making some final changes and i'll push!

**Comment by gigamesh** [comment]
looking forward to this!
