### ISSUE TITLE
FFI examples

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#182]
We should add some FFI examples

Pinging @FrankieIsLost; @gakonst said you had some nice ideas here :)

**Comment by FrankieIsLost** [comment]
Happy to take a first pass at a write-up this week. Here is one simple example: https://github.com/FrankieIsLost/gradual-dutch-auction/blob/master/src/test/DiscreteGDA.t.sol#L78 

I've been doing differential fuzzing (calling FFI over fuzzer inputs) on one of my current projects and it's be extremely helpful as well. Will open source soon, but can pull out an example for write-up.

**Comment by onbjerg** [comment]
That would be awesome :smile:

**Comment by dmfxyz** [comment]
I also implemented some basic FFI tests to standardize merkle proof testing here: https://github.com/dmfxyz/murky. Currently in the process of writing FFI tests that validate compatibility with [Uniswap/merkle-distributor](https://github.com/Uniswap/merkle-distributor). Happy to add a brief example writeup on this as well, if it's useful.

**Comment by gakonst** [comment]
Yeah an example writeup would be great!

**Comment by dmfxyz** [comment]
@onbjerg @gakonst @FrankieIsLost any ideas for a descriptive name for this type of testing? I've tried `cross-{language,functional,etc}-testing"`, `reference-testing`, and more that I've forgotten. Not in love with any of them.

**Comment by FrankieIsLost** [comment]
Differential testing! https://en.wikipedia.org/wiki/Differential_testing

**Comment by dmfxyz** [comment]
> Differential testing! https://en.wikipedia.org/wiki/Differential_testing 

Ah! Sweet. Thank you

**Comment by onbjerg** [comment]
Going to close this when #225 is merged, but absolutely do feel free to add more examples if you want to @FrankieIsLost :smile:

**Comment by FrankieIsLost** [comment]
Thanks! Just left a nit on the writeup, but looks great overall!
