### ISSUE TITLE
Document how to extend DSTest with your own assertion overloads

### ISSUE THREAD

**Issue by mds1** [foundry-rs/book#191]
A common question is how to `assertEq` on custom enum and struct types, and a common pattern for doing this is:
- In `test/utils`, create a file called `DSTestPlus.sol` which has a contract `DSTestPlus is DSTest`
- In that contract, add your own `assertEq` overloads (may as well define a `Vm` instance too). The overloads can either be:
    - Copy/pasted from `DSTest` and modified so you can override [the type shown in the log](https://github.com/dapphub/ds-test/blob/2c7dbcc8586b33f358e3307a443e524490c17666/src/test.sol#L159), or
    - Cast from e.g. enum to uint then just call another `assertEq` method
- Then have all your tests inherit from your own `DSTestPlus` instead of `DSTest`

**Comment by onbjerg** [comment]
I don't want to appeal to this, but isn't this sort of self-evident?

**Comment by mds1** [comment]
Arguably yes, but I've seen it get asked/used as an answer enough that I figured it would be helpful to have a paragraph about it in a "testing patterns" type of section (since I think that documenting common/useful test patterns somewhere has been discussed)

**Comment by onbjerg** [comment]
I addressed this in f7dcd3a6c47be7f3c7e1fc2838fef1f994376751, let me know if you feel like something is missing in that explanation :smile:

**Comment by mds1** [comment]
LGTM, thanks!
