### ISSUE TITLE
Write FAQ

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#201]
Some ideas for topics: https://github.com/gakonst/foundry/issues/536

Various troubleshooting for installation (see the Foundry README).

Others would be common questions in the support Telegram.

**Comment by ZeroEkkusu** [comment]
**Some notes**

- The user should name their `Vm` instance in `DSTestPlus` something other than `vm` if they plan on using Forge Std (otherwise will conflict with the `vm` there)
