### ISSUE TITLE
Document slither & mythril integrations

### ISSUE THREAD

**Issue by wminshew** [foundry-rs/book#212]
pulled from [this recent repo of mine](https://github.com/0xSplits/splits-vesting),

slither.config.json
```
{
  "filter_paths": "lib",
  "solc_remaps": [
    "ds-test/=lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
  ]
}
```

mythril.config.json
```
{
  "remappings": [
    "ds-test/=lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
  ],
  "optimizer": {
    "enabled": true,
    "runs": 200
  }
}
```

I struggled a bit to find/figure out the right config format (the original errors provided iirc were not particularly helpful in identifying it was a remapping issue, just a guess from my limited compiler knowledge). Have seen at least one other person recently on tg support group ask about it. Maybe good for an appendix page?

**Comment by onbjerg** [comment]
I think it makes sense to include it in the configuration section, where we also have stuff like VSCode and GitHub actions :smile:

**Comment by wminshew** [comment]
> I think it makes sense to include it in the configuration section, where we also have stuff like VSCode and GitHub actions 😄

totally :) opened a PR lmkwyt

**Comment by Elyx0** [comment]
A bit confused about this since I followed the foundry docs and added

- Mythril version v0.23.4

```json
{
    "remappings": [
      "openzeppelin-contracts/=lib/openzeppelin-contracts/",
      "ds-test/=lib/ds-test/src/",
      "forge-std/=lib/forge-std/src/"
    ],
    "optimizer": {
      "enabled": true,
      "runs": 200
    }
  }
  ```
  in a `mythril.config.json` at the root of my repo. 

And still get:

```
mythril.interfaces.cli [ERROR]: Solc experienced a fatal error.

ParserError: Source "openzeppelin-contracts/contracts/utils/Address.sol" not found: File not found. Searched the following locations: "".
 --> contracts/FastLaneAuction.sol:4:1:
  |
4 | import "openzeppelin-contracts/contracts/utils/Address.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
  
  I did not find any references of  `mythril.config.json` in https://mythril-classic.readthedocs.io/en/master/search.html?q=mythril.config.json&check_keywords=yes&area=default nor a reference to `remappings`
  
I ran it with `myth analyze myContract.sol`

Slither ran without any additional config using `slither . --compile-force-framework foundry --filter-paths 'test|lib'"` 

Any clues @wminshew ?

**Comment by wminshew** [comment]
@Elyx0 iirc I used docker via the below cmd:
```
docker run -it --rm -v$(pwd):/home/mythril mythril/myth -v4 analyze {{source}} --solc-json mythril.config.json --solv 0.8.13
```

found the referenced json config structure via this gh comment https://github.com/ConsenSys/mythril/issues/1452#issuecomment-973070338 (which pointed to this reference https://github.com/ConsenSys/mythril/blob/develop/tests/testdata/json_test_dir/test_file.json)

hopefully that helps -- gl!
