### ISSUE TITLE
Document revert strings config

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#234]
Document the `--revert-strings` flag and the `revert_strings` config value. See https://github.com/foundry-rs/foundry/pull/1377

**Comment by Leutwiler** [comment]
After some consideration, I think this topic is already well documented at https://book.getfoundry.sh/reference/config.html?#revert_strings

This part of the book does not explicitly tell the reader that you can pass the --revert-strings flag, so if this is a crucial information, I really think we should create a new section in the book called Flags, where we can write all the possible flags we can use in Foundry.

What do you think about that?

**Comment by onbjerg** [comment]
I think this page https://book.getfoundry.sh/reference/forge/forge-build.html is just missing the `--revert-strings` option
