### ISSUE TITLE
zsh completions script 

### ISSUE THREAD

**Issue by wiasliaw** [foundry-rs/book#261]
Where to place completions script in zsh might be wrong.

https://github.com/foundry-rs/book/blob/f5e8f9088293038cc272c54b3aac73e0efd397b8/src/config/shell-autocompletion.md?plain=1#L12-L18

According to [GitHub cli](https://cli.github.com/manual/gh_completion), should be

```bash
/usr/local/share/zsh/site-functions/_forge
/usr/local/share/zsh/site-functions/_cast
```

**Comment by onbjerg** [comment]
As noted in the guide, this is for people who use oh-my-zsh: https://github.com/foundry-rs/book/blob/f5e8f9088293038cc272c54b3aac73e0efd397b8/src/config/shell-autocompletion.md?plain=1#L5

Feel free to add an example for people that don't use oh-my-zsh :)

**Comment by wiasliaw** [comment]
Hi @onbjerg,

Im sure Im using oh-my-zsh for now. Since [v5.0.7](https://zsh.sourceforge.io/releases.html), the `$fpath` had been change. I will update it and make a PR.
