### ISSUE TITLE
Std Math Bug in Foundry Book

### ISSUE THREAD

**Issue by Leutwiler** [foundry-rs/book#266]
Hello! My pull request #259 was recently approved, but when I try to search for Std Math in the Foundry book site, there are no results for the main text, just for the additional parts in files which already existed beforehand. The Std Math topic also doesn't show up on the left bar nearby the other Std Libraries (Std Cheats, Std Errors and Std Storage).

So my issue is how can a new file published on Github be attached to the Foundry book website?

You can check the file in this link:

https://github.com/foundry-rs/book/blob/master/src/reference/forge-std/std-math.md

Thanks!

**Comment by onbjerg** [comment]
Ah, you forgot to add it to the summary file (`SUMMARY.md`).
