### ISSUE TITLE
Document Solidity Scripting

### ISSUE THREAD

**Issue by ZeroEkkusu** [foundry-rs/book#332]
See https://github.com/foundry-rs/foundry/pull/1208

**Comment by Perelyn-sama** [comment]
I would like to mess around with this👉👈

**Comment by ZeroEkkusu** [comment]
@Perelyn-sama Perhaps you can write a section about Solidity Scripting, after `Deploying and Verifying`. I think it deserves a dedicated section. Wdyt, @onbjerg?
