### ISSUE TITLE
Document `expectRevert` for custom errors

### ISSUE THREAD

**Issue by ChiTimesChi** [foundry-rs/book#333]
Documentation on how to properly check custom errors  being thrown would be nice.

See https://github.com/foundry-rs/foundry/issues/1007#issuecomment-1092067054

**Comment by mds1** [comment]
Also just to clarify the linked comment, you only need `abi.encodeWithSelector` if your custom error has arguments. If it doesn't you can just do `vm.expectRevert(MyCustomError.selector)`

**Comment by onbjerg** [comment]
This is already documented: https://book.getfoundry.sh/cheatcodes/expect-revert.html#examples :smile:
