### ISSUE TITLE
Document `--silent` flag

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#367]
See https://github.com/foundry-rs/foundry/pull/1820#event-6752318750

**Comment by Tirthnp** [comment]
@onbjerg Would --silent it be part of [Watch Options](https://book.getfoundry.sh/reference/forge/forge-build.html?highlight=forge%20build#watch-options) or [Compiler Options](https://book.getfoundry.sh/reference/forge/forge-build.html?highlight=forge%20build#compiler-options) ? And I am assuming the option will be the same for all `build`, `test`, and `create`?

**Comment by onbjerg** [comment]
It would be part of this file: https://github.com/foundry-rs/book/blob/master/src/reference/forge/core-build-options.md

**Comment by Tirthnp** [comment]
Would this look ?
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/19911354/173695822-b965a373-5c47-4910-aaa9-2a118d1a8d23.png">

**Comment by onbjerg** [comment]
@Tirthnp Ideally it should be but practically it does show up for all of those commands:

```
$ forge snapshot --help | grep silent
        --silent
```

**Comment by Tirthnp** [comment]
@onbjerg So does the params next to --silent makes sense ?

**Comment by onbjerg** [comment]
Oh sorry I missed that, no the path doesn't make sense since it doesn't take an argument

**Comment by Tirthnp** [comment]
@onbjerg I created PR https://github.com/foundry-rs/book/pull/384
