### ISSUE TITLE
Document `--etherscan` in `forge cache clean`

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#368]
See https://github.com/foundry-rs/foundry/pull/1807#issuecomment-1147549389

**Comment by 0xvv** [comment]
I think this was done in: https://github.com/foundry-rs/book/pull/362

**Comment by 0xvv** [comment]
The basic doc was added in: https://github.com/foundry-rs/book/pull/362

Is there more you think we should add ?
