### ISSUE TITLE
Add foundry scripting and deployments

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/book#382]
https://twitter.com/gakonst/status/1531056739470016512

I'm very excited to play with this stuff, would love to see it in the book!

**Comment by onbjerg** [comment]
It is already in the book :smile: https://book.getfoundry.sh/tutorials/solidity-scripting.html and https://book.getfoundry.sh/reference/forge/forge-script.html

**Comment by PatrickAlphaC** [comment]
Oh! I didn't know this!

Can we add to the deploying and verifying section though? I feel like this scripting / broadcasting will be the default for large projects:
<img width="279" alt="Screen Shot 2022-06-17 at 8 57 37 AM" src="https://user-images.githubusercontent.com/54278053/174302942-c08a984e-8c70-4b9e-bec1-6937c4d1d351.png">

**Comment by onbjerg** [comment]
This is tracked in https://github.com/foundry-rs/book/issues/377 but I don't think we should move the tutorial up in that section; those sections are for overviews of the feature, not necessarily an entire walkthrough from A-Z :)

**Comment by PatrickAlphaC** [comment]
Oh nice, already an issue!
