### ISSUE TITLE
Update auto-generated CLI output to separate command and output

### ISSUE THREAD

**Issue by sbvegan** [foundry-rs/book#433]
I'm starting to go through the book and the auto generated CLI output doesn't copy and paste well into the terminal because the, "$" is prepended to the command and the output is in the text box. 

I was thinking I could remove the, "$" from commands and separate them from their output so they can be directly copy and pasted into the terminal.

It's an opinionated change, but I thought it might make the UX a little better so I thought I'd pitch it. What do y'all think?

**Comment by skaunov** [comment]
I personally like it better as a "listing", i.e. just like it is now. Rough rationalization of it is that it's much easier to lookup something you need to refresh in your understandings when revisit the docs; and facilitation of copy-paste of examples could have even negative value taken broadly.

On July 9, 2022 5:24:14 AM GMT+03:00, soyboy ***@***.***> wrote:
>I'm starting to go through the book and the auto generated CLI output doesn't copy and paste well into the terminal because the, "$" is prepended to the command and the output is in the text box. 
>
>I was thinking I could remove the, "$" from commands and separate them from their output so they can be directly copy and pasted into the terminal.
>
>It's an opinionated change, but I thought it might make the UX a little better so I thought I'd pitch it. What do y'all think?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/foundry-rs/book/issues/433
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sbvegan** [comment]
@skaunov that makes sense, I personally even learn more when I write out the commands. I appreciate you sharing that perspective.
