### ISSUE TITLE
Restructure forking cheatcodes

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#454]
Restructure the forking cheatcodes (see https://github.com/foundry-rs/book/pull/442) to follow the same structure as other cheatcodes (e.g. put them in a new section and create index pages etc.)

**Comment by neodaoist** [comment]
This is a good first issue for me. I will do it.

**Comment by mattsse** [comment]
thanks!
but heads up, there'll be some changes https://github.com/foundry-rs/foundry/pull/2301

**Comment by neodaoist** [comment]
ok got it @mattsse. so no additional cheatcodes, but soon each fork will have its own separate storage area.

I reviewed `testForksHaveSeparatedStorage` and `testCanShareDataAcrossSwaps` from https://github.com/foundry-rs/foundry/pull/2301 and will make sure this behavior is clear on the relevant cheatcode pages.
