### ISSUE TITLE
Add note about "fatal: not removing recursively without -r"

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/book#459]
A common error when attempting to remove a git submodule is this:

> fatal: not removing 'lib/name' recursively without -r

It would be nice to add a note about this in the [Removing dependencies](https://book.getfoundry.sh/projects/dependencies#removing-dependencies) section, and what is the solution if users bump into this.

**Comment by onbjerg** [comment]
Pretty sure this was fixed recently?

**Comment by paulrberg** [comment]
It occurred multiple times for me, recently. But anyways, if this is supposed to be something that either was fixed or can be fixed in Forge itself, I'll close this issue here.
