### ISSUE TITLE
Document `--skip-simulation` on `forge script`

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#495]
See https://github.com/foundry-rs/foundry/pull/2524

**Comment by ckoopmann** [comment]
Not sure how the linked twitter content is relevant to this, but I'd be more than happy to tackle this together with https://github.com/foundry-rs/book/issues/496

**Comment by onbjerg** [comment]
Lmao, clipboard must have bugged :smile: Assigned you!
