### ISSUE TITLE
Document `vm.parseJson`

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/book#531]
See https://github.com/foundry-rs/foundry/pull/2293

**Comment by mds1** [comment]
FWIW the cheat interface is not yet in forge-std, I'm planning to try to PR that in today or tomorrow but we should probably make sure that gets in first so the info in the docs actually works

**Comment by onbjerg** [comment]
Generally agree but I don't think the book should block Forge Std and the other way around until we do more coordinated releases :smile:

**Comment by odyslam** [comment]
Fixed in #584
