### ISSUE TITLE
Document jq usage in parseJson docs

### ISSUE THREAD

**Issue by chad-js** [foundry-rs/book#647]
Currently, the [parseJson docs](https://book.getfoundry.sh/cheatcodes/parse-json#instructions) don't explicitly mention that [jq](https://earthly.dev/blog/jq-select/) syntax must be used to reference keys in a json string/file.

**Comment by mattsse** [comment]
cc @odyslam

**Comment by odyslam** [comment]
That's a good point that I completely forgot about it. Thank you!
