### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by holic** [foundry-rs/book#659]
Navigating through menus to find a particular command or set of docs is getting tricky now that there's a bunch of categories. It'd be great if we could search with Algolia or similar.

**Comment by mattsse** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/19890894/193258840-2530b28b-149e-4331-a2af-922e94b9df5a.png">

there is search: 🔍

**Comment by holic** [comment]
Oops, I overlooked that tiny icon. 🙈
