### ISSUE TITLE
Where is the toString function in the forge-std lib? 

### ISSUE THREAD

**Issue by JonoPrest** [foundry-rs/book#668]
I see that toString is a documented function in the references but I'm not sure how to access it when installing the forge-std library. Is it an upcoming feature that hasn't been implemented yet? Or is it a deprecated feature? Thanks!

https://github.com/foundry-rs/book/blob/07a45eadad6a3d732de6d9c72523c1110cdb7596/src/cheatcodes/to-string.md?plain=1#L6-L11

**Comment by mds1** [comment]
Run `forge update` to make sure you're on the latest forge-std. You can see these cheats here on the current master (commit 2a2ce36): https://github.com/foundry-rs/forge-std/blob/master/src/Vm.sol#L147-L153

**Comment by JonoPrest** [comment]
> Run `forge update` to make sure you're on the latest forge-std. You can see these cheats here on the current master (commit 2a2ce36): https://github.com/foundry-rs/forge-std/blob/master/src/Vm.sol#L147-L153

Thanks so much! This worked perfectly 👌🏼
