### ISSUE TITLE
Why all of the sudden Foundry throws permission error when build

### ISSUE THREAD

**Issue by MiguelBits** [foundry-rs/book#670]
```Failed to create artifact parent folder "/_1/home/miguelbits/Desktop/blabla/blabla/out/Helper.sol": Permission denied (os error 13)```  
There is no "/_1/" directory in my laptop, why does foundry even think there is one?  
Where can I fix this

**Comment by mattsse** [comment]
closing as dup of https://github.com/foundry-rs/foundry/issues/3268

this is a weird one, and appears to be related to how paths are canonicalized.

is there a way to reproduce this consistently?

**Comment by MiguelBits** [comment]
fixed this by changing the `foundry.toml` , renaming "out" to "somethingelse"

**Comment by MiguelBits** [comment]
thank you for being so quick to reply :dancing_men:
