### ISSUE TITLE
Error when compiling NFT tutorial code

### ISSUE THREAD

**Issue by thomasbach-dev** [foundry-rs/book#687]
Taking the code from the “Implementing a basic NFT” section (https://book.getfoundry.sh/tutorials/solmate-nft#implement-a-basic-nft) in the NFT Tutorial, I get a compilation error:

```
 forge build
[⠒] Compiling...
[⠆] Compiling 5 files with 0.8.13
[⠰] Solc 0.8.13 finished in 23.37ms
Error: 
Compiler run failed
error[6275]: ParserError: Source "lib/openzeppelin-contracts/contracts/contracts/utils/Strings.sol" not found: File not found. Searched the following locations: "PATH/TO/REPOBASE/foundry-playground".
 --> src/NFT.sol:5:1:
  |
5 | import "openzeppelin-contracts/contracts/utils/Strings.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I installed the library and can find the following path: `lib/openzeppelin-contracts/contracts/utils/Strings.sol`.

**Comment by Sabnock01** [comment]
Did you put the remappings in `foundry.toml` or `ramappings.txt`?

**Comment by Sabnock01** [comment]
And how did you install the library? Through `forge install` or `npm`?

**Comment by thomasbach-dev** [comment]
No, there was no remapping. So I just executed
> forge re > remappings.txt

The error stays the same.

> Did you put the remappings in `foundry.toml` or `ramappings.txt`?

**Comment by thomasbach-dev** [comment]
> And how did you install the library? Through `forge install` or `npm`?

Using `forge install transmissions11/solmate Openzeppelin/openzeppelin-contracts`.

**Comment by thomasbach-dev** [comment]
btw: current code can be found here: https://github.com/thomasbach-dev/foundry-playground/tree/nft-with-solmate

I used nix to install foundry via https://github.com/shazow/foundry.nix

**Comment by mattsse** [comment]
this looks like an issue with the remappings auto-detection that wrongly concatenates `contracts` twice.

you should be able to fix this by adding a oz remappings directly into foundry.toml

**Comment by thomasbach-dev** [comment]
Nice, I was indeed able to get the build running by adding
> remappings = ['openzeppelin-contracts/=lib/openzeppelin-contracts/']

to `foundry.toml`.
