### ISSUE TITLE
When i type forge init --force / forge init 

### ISSUE THREAD

**Issue by pavankv241** [foundry-rs/book#703]
It give this error :-
ZOE ERROR (from forge): zoeParseOptions: unknown option (--force)
ZOE library version 2013-02-16

it's snap error pre-installed in linux , so snap revokes foundry operation.

Anyone please help .

**Comment by pavankv241** [comment]
anvil is running 
but not foundry command

**Comment by onbjerg** [comment]
Please reach out on Telegram as this is not a bug in Foundry or in the book and it is easier to figure out what is happening there 🙂

**Comment by vickyone0** [comment]
i also face same issue. anyone know about it
