### ISSUE TITLE
I used the uniswapV2 project in my project, but I encountered compilation problems, what should I do?

### ISSUE THREAD

**Issue by zh19910202** [foundry-rs/book#708]
![image](https://user-images.githubusercontent.com/34837173/203724738-a8ea84d7-95d7-421f-b3ed-d2e89825b9f4.png)

**Comment by mattsse** [comment]
you're tree uses incompatible versions:

`=0.6.6` and `0.8.15`

to fix this either down or upgrade the contracts.

**Comment by onbjerg** [comment]
Closing this as per above comment, but if you encounter more issues please ask on Telegram
