### ISSUE TITLE
git clone TROUBLE -- Invalid Parameter

### ISSUE THREAD

**Issue by coldstar1993** [foundry-rs/book#726]
Hi, team, 
When I git clone the repo, meeting trouble as belows:
```
fatal: cannot create directory at 'src/images/solidity-scripting ': invalid parameter
```
The root cause is the extra blank string in this dir name:
![image](https://user-images.githubusercontent.com/92623877/206414491-aa05e47c-a07d-4b04-82f9-683ec6c5a847.png)

This is my pr for this
https://github.com/foundry-rs/book/pull/727

**Comment by mattsse** [comment]
closed by #727
