### ISSUE TITLE
There is an incorrect url in the example code

### ISSUE THREAD

**Issue by LowLowCoder-Mel** [foundry-rs/book#739]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/10645606/209253286-06c9b89c-ff1f-4734-9e77-1f3bc4704f9f.png">

The correct url is:
https://eth-mainnet.g.alchemy.com/v2/ALCHEMY_KEY

**Comment by mattsse** [comment]
right, do you wanna fix this in a PR?
