### ISSUE TITLE
Suggestion to add two new test naming best practices

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/book#761]
The [General Test Guidance](https://book.getfoundry.sh/tutorials/best-practices#general-test-guidance) section lists out the following recommendations for how to name test functions:

- `test_Description`
- `testFuzz_Description`
- `test_Revert[If|When]_Description`
- `testFork_Description`
- `testForkFuzz_Revert[If|When]_Description`

My suggestion is to add two more test naming suggestions:

1. `testFuzz_Revert[If|When]_Description` - test that fuzzes and expects a revert
2. `testForkFuzz_Description` - test that fuzzes on a fork, but which does not expect a revert

As a side note, if this proposal is accepted, it might be worth adding support for these in the [scopelint](https://github.com/ScopeLift/scopelint) as well.

**Comment by paulrberg** [comment]
Yeah, pasting the regex would be helpful, though it should be added after the examples are given. I think that humans have a hard time reading regexes without examples.

> Adding `RevertOn` as another allowed case

SGTM

> Removing `RevertWhen`

I like "when" much better than "if", because "when" refers to a situation that is more concise, and about which one is more certain of.

If it doesn't cost you a lot in terms of maintenance costs, I would be in favor of keeping both "if" and "when" as connectors for "Revert".

> the former is more concise

Perhaps you meant to say "latter"?

**Comment by paulrberg** [comment]
Quick question about the regex, @mds1.

Does it support additional underscores after `Description`? I have lots and lots of standard test functions named like this:

```text
test_Description1_Description2
```

If not, I would like to suggest this as a feature request.

**Comment by mds1** [comment]
> Yeah, pasting the regex would be helpful, though it should be added after the examples are given. I think that humans have a hard time reading regexes without examples.

Agreed

> I like "when" much better than "if", because "when" refers to a situation that is more concise, and about which one is more certain of.
> 
> If it doesn't cost you a lot in terms of maintenance costs, I would be in favor of keeping both "if" and "when" as connectors for "Revert".

Sgtm, I'm ok with keeping both (and yes I did mean "latter", whoops)

> Does it support additional underscores after `Description`? I have lots and lots of standard test functions named like this:

That is supported! The regex ends with `\w+` which allows all lowercase and capital letters, all numbers, and underscores

Let me make the above regex updates this week and I'll get a corresponding book PR in as well that adds some clarity

**Comment by paulrberg** [comment]
> That is supported! The regex ends with `\w+` which allows all lowercase and capital letters, all numbers, and underscores

Perfect!
