### ISSUE TITLE
Update Hardhat guide to use the hardhat-foundry plugin

### ISSUE THREAD

**Issue by fvictorio** [foundry-rs/book#773]
Now that we've published our [hardhat-foundry](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-foundry) plugin, it would be nice to update this section of the Foundry book to use in instead of using `hardhat-preprocessor`. I think this needs two PRs:

- One in this repo to update that guide
- One in the [hardhat-foundry-template](https://github.com/foundry-rs/hardhat-foundry-template) repo to use the new plugin

I'm happy to do both, but I would like to have confirmation first that this is something you want to do.

**Comment by gakonst** [comment]
Oh only just saw this. Yeah supportive, let's do it.

**Comment by fvictorio** [comment]
Closing in favor of https://github.com/foundry-rs/book/issues/1033
