### ISSUE TITLE
Add information how to work with OZ proxies

### ISSUE THREAD

**Issue by unordered-set** [foundry-rs/book#837]
I wrote a small article about it https://teletype.in/@xni/ZGY6w5o9PYy but I think it should be a part of a book, as OZ proxies exists in 100% of my projects

**Comment by zerosnacks** [comment]
Thanks @unordered-set for the suggestion, open to having it be included but otherwise not planned considering it is more related to the specific implementation and would rather point users to the excellent documentation of OpenZeppelin - considering this is sensitive in its configuration.
