### ISSUE TITLE
Update testing functions examples with best practices

### ISSUE THREAD

**Issue by urataps** [foundry-rs/book#842]
Hello forgers,

I spotted an inconsistency in the documentation. The Forge Guide part of the book is not up to date with the [testing best practices](https://book.getfoundry.sh/tutorials/best-practices#general-test-guidance) described in the Tutorials chapter.

More specifically, the provided test functions examples do not comply with the following pattern, also outlined [here](https://github.com/ScopeLift/scopelint/blob/1857e3940bfe92ac5a136827374f4b27ff083971/src/check/validators/test_names.rs#L106-L143):

- `test_Description` for standard tests.
- `testFuzz_Description` for fuzz tests.
- `test_Revert[If|When]_Condition` for tests expecting a revert.
- `testFork_Description` for tests that fork from a network.
- `testForkFuzz_Revert[If|When]_Condition` for a fuzz test that forks and expects a revert.

This can lead newcomers on an unscrupulous path of writing unclear tests and thus have bad coverage.  

To fix this, we would need to update the solidity contracts from the `projects` folder.

I can open a PR for dis.

**Comment by mds1** [comment]
Closed by #843? cc @mattsse
