### ISSUE TITLE
"Failed Reason: stdStorage find(StdStorage): Slot(s) not Found" when calling a contract with staticcall

### ISSUE THREAD

**Issue by Sitthiput** [foundry-rs/book#849]
Hi, I'm trying to test my contract, in this case, I want to call with staticcall to Curve's pool contract to get the value. However, I ended up with this error. I could not figure out why nor find the answer for this one anywhere.

![image](https://user-images.githubusercontent.com/40175814/224830421-feda979c-5bf8-4241-8e6c-307828e734d3.png)
![image](https://user-images.githubusercontent.com/40175814/224830295-834ee6d8-ebb0-4d7a-9723-cf618a30d6cb.png)

**Comment by 0xtr3** [comment]
Hello. What was the resolve for this please? I have the same issue.
