### ISSUE TITLE
Test files used with the vscode-solidity extension slows down intellisense considerably

### ISSUE THREAD

**Issue by FHieser** [foundry-rs/book#858]
As the name implies the usage of the vs code extension "vscode-solidity" (https://github.com/juanfranblanco/vscode-solidity) with foundry test files slows down the intellisense capabilites of that extension by a significant proportion.

Maybe some info about this:
- I'm working on a Ubuntu system
- it seems to be only happening in foundry Testfiles (.t.sol) that inherit "forge-std/Test.sol"
- When I press ctrl+space-bar for autocompletion one of my CPUs goes straight to 100% workload but it doesnt load any possible suggestions
- It seems to me that there is something with the auto recognition that slows the whole system so much it doesnt update properly

There is a congruent issue on the vscode-solidity side here (https://github.com/juanfranblanco/vscode-solidity/issues/401)

**Comment by Evalir** [comment]
Closing, stale and wrong repo. If this is still a problem, please reopen on the foundry codebase repo.
