### ISSUE TITLE
No mention of `forge coverage` in the docs

### ISSUE THREAD

**Issue by nnnnicholas** [foundry-rs/book#861]
Searching the docs with the built in search tool and google, there does not appear to be any mention of `forge coverage`.

If true, a page describing `coverage` could be added to the `Test Commands` area. A docs page for `coverage` could draw inspiration from this post by devanon and mention the VSCode formatting tip: https://mirror.xyz/devanon.eth/RrDvKPnlD-pmpuW7hQeR5wWdVjklrpOgPCOA-PJkWFU

<img width="207" alt="image" src="https://user-images.githubusercontent.com/1418561/230190955-c7a594d9-0b1d-4d6e-8488-90efafd3bb6e.png">

**Comment by ChefAharoni** [comment]
Looks like this issue can be closed, as it has been added to the [docs](https://book.getfoundry.sh/reference/forge/forge-coverage?highlight=coverage#forge-coverage).
