### ISSUE TITLE
Document `dictionary_weight`

### ISSUE THREAD

**Issue by aviggiano** [foundry-rs/book#893]
What does [`dictionary_weight`](https://book.getfoundry.sh/reference/config/testing?highlight=dictionary_wei#dictionary_weight) mean and how does it affect the fuzzer performance? I can't find any docs related to it.

**Comment by wildmolasses** [comment]
@aviggiano ran into this issue myself; see [this comment](https://github.com/foundry-rs/foundry/issues/387#issuecomment-1034396200) from @mds1 that gets at what `dictionary_weight` means.
