### ISSUE TITLE
chore: document best practices for blockchain time management in invariant tests

### ISSUE THREAD

**Issue by JacoboLansac** [foundry-rs/book#899]
When doing invariant tests on a staking protocol, it is important to be able to simulate the passing of time. I tried two approaches:

Adding a function to a handler contract that internally uses skip(time). However, the blockchain timestamp was reverted to the original point after executing the function. Time advancement was not preserved outside that function.

In the handler contract, declare a state variable called timestamp and add a modifier to all functions in the handler contract, which would add some time to that variable before using vm.warp(timestamp). This worked.

Is there a better way of doing it?

--- Note ---
This issue was first open in the foundry-rs repo, but it was suggested to bring it up to this other repo. Find the link to the other issue, with the responses:
https://github.com/foundry-rs/forge-std/issues/376

**Comment by zerosnacks** [comment]
cc @grandizzy possibly already covered but otherwise could be relevant

**Comment by grandizzy** [comment]
@zerosnacks yeah, that behavior was fixed with https://github.com/foundry-rs/foundry/pull/7819 so no additional management needed for time in invariant tests
