### ISSUE TITLE
Add chain id to anvil output

### ISSUE THREAD

**Issue by jtardioli** [foundry-rs/book#929]
I'm going through Patrick Collin's Foundry course and am currently at the part where you link Anvil to MetaMask, I noticed the default chain id for Anvil isn't clearly stated in the documentation. Without the course I don't think I would have found the information. I propose adding this detail to the page below for better accessibility: 

https://book.getfoundry.sh/reference/anvil/ 

PS. If it is clearly stated and I'm blind ignore this 😛

**Comment by mattsse** [comment]
good point, we should include this in the default output

FYI there's also `cast chain-id` or `cast rpc eth_chainId`

**Comment by jtardioli** [comment]
What do you think about adding it here? I could do a quick pr

https://book.getfoundry.sh/reference/anvil/#executor-environment-config
![image](https://github.com/foundry-rs/book/assets/85530348/c4fccfbf-753c-4ee8-88a5-e36b664faf42)

**Comment by Evalir** [comment]
@jtardioli that looks good! def feel free to send in a pr :)
