### ISSUE TITLE
RUST_LOG description

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/book#937]

**Comment by Evalir** [comment]
I assume the desired thing here is to document `RUST_LOG` which we use to show additional traces when debugging and sometimes when reporting issues.

**Comment by Evalir** [comment]
Closing—rather than adding a section to the book for debugging, we'll point it out on the main repo and on issue templates.

**Comment by mds1** [comment]
> I assume the desired thing here is to document `RUST_LOG` which we use to show additional traces when debugging and sometimes when reporting issues.

Documenting this and other debugging tips does seem useful, just to clarify are you suggesting not to add debugging-related docs to the book?

**Comment by Evalir** [comment]
Yep@mds1 I think that debugging tips meant for _us_ to look into foundry might be better put on issue templates and main repro (`CONTRIBUTING.md`)—The debug logs don't mean a lot to the average user. However, maybe it's worth having a "reporting issues" section on the book?

**Comment by mds1** [comment]
> However, maybe it's worth having a "reporting issues" section on the book?

That seems reasonable to me! And we can link to that section of the book from the issue template

**Comment by Evalir** [comment]
Awesome! Let's do it then. I'll keep this issue closed and create a more appropiate new one ^^ @mds1
