### ISSUE TITLE
Deserialization Error: EOF while parsing a value at line 1 column 0. Response: 

### ISSUE THREAD

**Issue by muraneth** [foundry-rs/book#949]
got problem when running  "forge create --rpc-url http://127.0.0.1:8545  --private-key  ....  src/Counter.sol:Counter"

Problem : Deserialization Error: EOF while parsing a value at line 1 column 0. Response: 
<img width="825" alt="image" src="https://github.com/foundry-rs/book/assets/101977416/6002302e-9e08-4a41-9cc3-f435e717776c">

**Comment by zerosnacks** [comment]
It means that you received a non-JSON error, often related to a network connection being dropped.

Related: https://github.com/foundry-rs/foundry/issues/7484
