### ISSUE TITLE
command not found: tree

### ISSUE THREAD

**Issue by worksofallwin** [foundry-rs/book#964]
After project initialization.

If we run the following command,
```
tree . -d -L 1
```
command not found: tree 

Should there be more info about it, 
before running this command, make sure you have `tree` installed on your machine.
If not, install it using `brew install tree`  for `mac`. 
Also info about installing on `linux` and `windows`

**Comment by Evalir** [comment]
This is easily googleable 😅 but happy to see you contribute to the book to add these instructions to the book!
