### ISSUE TITLE
Documents `assertNotEq`

### ISSUE THREAD

**Issue by 0xb10ckdev** [foundry-rs/book#988]
Documents for `assertNotEq` is missed in `DSTest Reference`
https://book.getfoundry.sh/reference/ds-test?highlight=assert#asserting

**Comment by ATREAY** [comment]
Hey @0xb10ckdev, is it okay if I work on this issue if you haven't started on it? 
Also, could you please share the reference/link where I can find information about `assertNotEq`?

**Comment by zerosnacks** [comment]
It is not part of `DSTest` but rather of `forge-std`: https://book.getfoundry.sh/reference/forge-std/assertNotEq
