### ISSUE TITLE
vm.sign example doesnt work

### ISSUE THREAD

**Issue by devtooligan** [foundry-rs/book#991]
https://book.getfoundry.sh/cheatcodes/sign?highlight=vm.sign#examples

<img width="1213" alt="Screenshot 2023-08-23 at 11 40 00 AM" src="https://github.com/foundry-rs/book/assets/71567643/c164f7c5-709e-4b1a-b7c6-04a69f5466ba">

**Comment by devtooligan** [comment]
this worked for me:  (i can amke a pr later)
```
contract Test85 is Test {
    function test_sign() external {
        uint alicePk = uint(0x69);
        address alice = vm.addr(alicePk);
        bytes32 hash = keccak256("Signed by Alice");
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(alicePk, hash);
        address signer = ecrecover(hash, v, r, s);
        assertEq(alice, signer); // [PASS]
    }
}
```

**Comment by Sabnock01** [comment]
The problem here is the original example uses a private key of `1` which is incorrect. This can be easily solved by swapping `makeAddr` with `makeAddrAndKey`.
